# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuData = QtWidgets.QMenu(parent=self.menubar)
        self.menuData.setObjectName("menuData")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionfrom_folder = QtGui.QAction(parent=MainWindow)
        self.actionfrom_folder.setObjectName("actionfrom_folder")
        self.actionfrom_site = QtGui.QAction(parent=MainWindow)
        self.actionfrom_site.setObjectName("actionfrom_site")
        self.menuData.addAction(self.actionfrom_folder)
        self.menuData.addAction(self.actionfrom_site)
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(MainWindow)
        self.actionfrom_folder.triggered.connect(MainWindow.selectFile) # type: ignore
        self.actionfrom_site.triggered.connect(MainWindow.open_second_window) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.actionfrom_folder.setText(_translate("MainWindow", "from folder"))
        self.actionfrom_site.setText(_translate("MainWindow", "from site"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
